### PR TITLE
verup to 0.10.0

### PR DESCRIPTION
**Pull request by zaherg**

### CODE REVIEW

**Comment by gavinzhou** [comment]
@linuxjuggler 
thank your PR, 
Can help modify the test case with check.sh

**Comment by zaherg** [comment]
@gavinzhou sure, I'll try to do that today or so.

**Comment by zaherg** [comment]
am not ignoring this but I have small personal issues to solve.

**Comment by gavinzhou** [comment]
@linuxjuggler 
And the 0.9x version has a lot of changes, I will fix the `check.sh` scripts.

I use quay.io scan kong images, get two security issues.

https://quay.io/repository/orangesys/alpine-kong/image/6bbc2c9e1ef1e3453fa5ada743984f17f4b09768e726beb1dd0ad4fa00e8b9cb?tab=vulnerabilities

Fix the following two security issues

**Comment by gavinzhou** [comment]
@linuxjuggler 
I upgrade kong with 0.10.1 and fix `check.sh`
you can get this image with docker hub.
I add quay.io security scan

I will close this PR.
Thank you!

**Comment by zaherg** [comment]
thanks and really sorry that I didnt had the time to fix check.sh, maybe next time.

**Pull request closed without merging**
